### ISSUE TITLE
backend validation

### ISSUE THREAD

**Issue by hueitan** [thetutlage/angular-validation-schema#1]
This is for client-side angular validation used.

How about using the same one for back-end side validation? 

using the `require` and `window` to detect client and server.

**Comment by thetutlage** [comment]
didn't get that ? using require and window ?

**Comment by hueitan** [comment]
No, just my imagin.

Can we use the same angular-validation-schema.js both on client and server side.

**Comment by thetutlage** [comment]
No i don't think so

**Comment by hueitan** [comment]
Ok, just some imagination Xd
