### ISSUE TITLE
gh-pages DEMO page?

### ISSUE THREAD

**Issue by hueitan** [thetutlage/angular-validation-schema#2]
How about implement a demo page for it?

**Comment by thetutlage** [comment]
Created a plunk instead http://plnkr.co/edit/X56HEsDYgYoY8gbSj7cu?p=preview

**Comment by hueitan** [comment]
The DEMO doesn't work for me =(

**Comment by thetutlage** [comment]
Okay i referring files from raw.github so chrome throws an exception while including files. Will fix it

**Comment by thetutlage** [comment]
Fixed

**Comment by hueitan** [comment]
yeah! It's work now! 

Thanks!

BTW, nice trick :+1:
