### ISSUE TITLE
Change provider to factory?

### ISSUE THREAD

**Issue by rikumalminiemi** [thetutlage/angular-validation-schema#5]
Hi,
Is it possible to consider changing configuration from provider to factory? In my particular use case, this change would allow the usage of Angular-gettext for translations. I tested the change and at least in my project it worked fine with following code:

var app = angular.module('validation.schema',[])

```
// Tiny provider to save and fetch schemas
.factory('validationSchema',function(){

        var factory = {};
    // List of schemas are stored here
    var schemas = {};

    // Adding schema to object
        factory.set = function(name,hash){
        schemas[name] = hash;
    };

    // fetching from object
        factory.get = function(name){
        return schemas[name];
    }

    // Exposing them here
    return factory;
})
```

And configuration:

app.run(function (validationSchema, gettextCatalog) {
        validationSchema.set("User", User(gettextCatalog));
    });

**Comment by hueitan** [comment]
Looks fine.

But do you got any issue using the current version?

**Comment by rikumalminiemi** [comment]
This one can be closed, I found a better way around with small modifications to angular-validation itself :)

**Comment by hueitan** [comment]
Show us if you think we can improve angular-validation :beers:
